// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Validator__Core3 = require("./Validator__Core3.js");
var Validator__StringValidators3 = require("./Validator__StringValidators3.js");

var myValidator = Curry._2(Validator__Core3.Impl.Infix.$pipe$pipe, Curry._2(Validator__Core3.Impl.Infix.$pipe$pipe, Validator__StringValidators3.isLongerThan(10), Validator__StringValidators3.isLongerThan(11)), Validator__StringValidators3.isLongerThan(12));

console.log("Validator:", myValidator);

var result = Validator__Core3.validate(undefined, myValidator, "Hello");

console.log("Result:", result);

console.log(result._0);

exports.myValidator = myValidator;
exports.result = result;
/* myValidator Not a pure module */
