// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Validator__Core = require("./Validator__Core.js");

function shorterThan(length) {
  return Validator__Core.make({
              name: "shorterThan(" + length + ")",
              validate: (function (str) {
                  if (str.length < length) {
                    return /* Pass */0;
                  } else {
                    return /* Fail */{
                            _0: ""
                          };
                  }
                })
            });
}

function longerThan(length) {
  return Validator__Core.make({
              name: "longerThan(" + length + ")",
              validate: (function (str) {
                  if (str.length < length) {
                    return /* Pass */0;
                  } else {
                    return /* Fail */{
                            _0: ""
                          };
                  }
                })
            });
}

var isHelloWorld = Validator__Core.make({
      name: "isHelloWorld",
      validate: (function (str) {
          var match = str.trim().toLowerCase();
          switch (match) {
            case "hello  world" :
            case "hello  world!" :
            case "hello world" :
            case "hello world!" :
            case "helloworld" :
            case "helloworld!" :
                return /* Pass */0;
            default:
              return /* Fail */{
                      _0: "Expected some variation of \"Hello World\", but got \"" + str + "\" instead"
                    };
          }
        })
    });

var emailRegex = /^(([^<>()\[\]\.,;:\s@"]+(\.[^<>()\[\]\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

var isEmail = Validator__Core.make({
      name: "isEmail",
      validate: (function (str) {
          if (emailRegex.test(str)) {
            return /* Pass */0;
          } else {
            return /* Fail */{
                    _0: "Expected input to be a valid email address, but got " + str
                  };
          }
        })
    });

var Impl = {
  shorterThan: shorterThan,
  longerThan: longerThan,
  isHelloWorld: isHelloWorld,
  emailRegex: emailRegex,
  isEmail: isEmail
};

exports.Impl = Impl;
exports.shorterThan = shorterThan;
exports.longerThan = longerThan;
exports.isHelloWorld = isHelloWorld;
exports.emailRegex = emailRegex;
exports.isEmail = isEmail;
/* isHelloWorld Not a pure module */
