// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Validator__Core = require("./Validator__Core.js");

function shorterThan(length) {
  return Validator__Core.make({
              name: "shorterThan(" + length + ")",
              validate: (function (str) {
                  if (str.length < length) {
                    return /* Pass */0;
                  } else {
                    return /* Fail */{
                            _0: ""
                          };
                  }
                })
            });
}

function longerThan(length) {
  return Validator__Core.make({
              name: "longerThan(" + length + ")",
              validate: (function (str) {
                  if (str.length < length) {
                    return /* Pass */0;
                  } else {
                    return /* Fail */{
                            _0: ""
                          };
                  }
                })
            });
}

var isHelloWorld = Validator__Core.make({
      name: "isHelloWorld",
      validate: (function (str) {
          var match = str.trim().toLowerCase();
          switch (match) {
            case "hello  world" :
            case "hello  world!" :
            case "hello world" :
            case "hello world!" :
            case "helloworld" :
            case "helloworld!" :
                return /* Pass */0;
            default:
              return /* Fail */{
                      _0: "Expected some variation of \"Hello World\", but got \"" + str + "\" instead"
                    };
          }
        })
    });

var Impl = {
  shorterThan: shorterThan,
  longerThan: longerThan,
  isHelloWorld: isHelloWorld
};

exports.Impl = Impl;
exports.shorterThan = shorterThan;
exports.longerThan = longerThan;
exports.isHelloWorld = isHelloWorld;
/* isHelloWorld Not a pure module */
