// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Validator__Core = require("./Validator__Core.js");
var Validator__StringValidators = require("./Validator__StringValidators.js");

var myValidator = Curry._2(Validator__Core.Impl.Infix.$pipe$pipe, Curry._2(Validator__Core.Impl.Infix.$pipe$pipe, Curry._2(Validator__Core.Impl.Infix.$amp$amp, Curry._1(Validator__Core.Impl.Infix.not, Validator__StringValidators.shorterThan(100)), Curry._1(Validator__Core.Impl.Infix.not, Validator__StringValidators.longerThan(5))), Validator__StringValidators.isHelloWorld), Validator__StringValidators.isEmail);

console.log("Validator:", myValidator);

var result = Validator__Core.evalSync(myValidator, "Hi");

console.log("Result:", result);

if (result.TAG === /* Ok */0) {
  var match = result._0;
  console.log("PASSED");
  $$Array.iter((function (prim) {
          console.log(prim);
          
        }), match.passed);
  console.log("FAILED");
  $$Array.iter((function (prim) {
          console.log(prim);
          
        }), match.failed);
} else {
  var match$1 = result._0;
  console.log("PASSED");
  $$Array.iter((function (prim) {
          console.log(prim);
          
        }), match$1.passed);
  console.log("FAILED");
  $$Array.iter((function (prim) {
          console.log(prim);
          
        }), match$1.failed);
}

exports.myValidator = myValidator;
exports.result = result;
/* myValidator Not a pure module */
