// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Validator__Core = require("./Validator__Core.js");
var Validator__StringValidators = require("./Validator__StringValidators.js");

var myValidator = Curry._2(Validator__Core.Impl.Infix.$pipe$pipe, Curry._2(Validator__Core.Impl.Infix.$pipe$pipe, Validator__StringValidators.isLongerThan(10), Validator__StringValidators.isLongerThan(11)), Validator__StringValidators.isLongerThan(12));

console.log("Validator:", myValidator);

var result = Validator__Core.validate(undefined, myValidator, "Hello");

if (result.TAG === /* Ok */0) {
  console.log(result._0);
} else {
  console.log(result._0.errors);
}

exports.myValidator = myValidator;
exports.result = result;
/* myValidator Not a pure module */
