// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Validator__Core2 = require("./Validator__Core2.js");
var Validator__StringValidators2 = require("./Validator__StringValidators2.js");

var myValidator = Curry._2(Validator__Core2.Impl.Infix.$pipe$pipe, Curry._2(Validator__Core2.Impl.Infix.$pipe$pipe, Validator__StringValidators2.isLongerThan(10), Validator__StringValidators2.isLongerThan(11)), Validator__StringValidators2.isLongerThan(12));

console.log("Validator:", myValidator);

var result = Validator__Core2.evalSync(myValidator, "Hello");

console.log("Result:", result);

console.log(result._0);

exports.myValidator = myValidator;
exports.result = result;
/* myValidator Not a pure module */
