// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Validator__Core2 = require("./Validator__Core2.js");

function isShorterThan(length) {
  var name = "isShorterThan(" + length + ")";
  return Validator__Core2.make(name, (function (value) {
                return Validator__Core2.defaultErrorMessage(undefined, name, value);
              }), (function (str) {
                return str.length < length;
              }));
}

function isLongerThan(length) {
  var name = "isLongerThan(" + length + ")";
  return Validator__Core2.make(name, (function (value) {
                return Validator__Core2.defaultErrorMessage(undefined, name, value);
              }), (function (str) {
                return str.length > length;
              }));
}

var isHelloWorld = Validator__Core2.make("isHelloWorld", undefined, (function (str) {
        var match = str.trim().toLowerCase();
        switch (match) {
          case "hello  world" :
          case "hello  world!" :
          case "hello world" :
          case "hello world!" :
          case "helloworld" :
          case "helloworld!" :
              return true;
          default:
            return false;
        }
      }));

var emailRegex = /^(([^<>()\[\]\.,;:\s@"]+(\.[^<>()\[\]\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

var isEmail = Validator__Core2.make("isEmail", undefined, (function (str) {
        return emailRegex.test(str);
      }));

var Impl = {
  isShorterThan: isShorterThan,
  isLongerThan: isLongerThan,
  isHelloWorld: isHelloWorld,
  emailRegex: emailRegex,
  isEmail: isEmail
};

exports.Impl = Impl;
exports.isShorterThan = isShorterThan;
exports.isLongerThan = isLongerThan;
exports.isHelloWorld = isHelloWorld;
exports.emailRegex = emailRegex;
exports.isEmail = isEmail;
/* isHelloWorld Not a pure module */
